name: Check code goodness

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with: 
        dotnet-version: '3.0.100'
    - run: dotnet tool restore
    - name: Check formatting
      run: dotnet-format
