name: Check code goodness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.0.100'
    - run: dotnet tool restore
    - run: dotnet format --check --dry-run --workspace GraphQL.DynamoDb.sln
    - run: dotnet restore GraphQL.DynamoDb.sln
    - run: dotnet build GraphQL.DynamoDb.sln
