name: Check code goodness

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: dotnet tool install -g dotnet-format
    - name: Check formatting
      run: dotnet format
